#!/bin/sh
set -e
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ \
    --exclude=.git \
    --exclude=node_modules \
    --exclude=.eggs \
    --exclude=.tox \
    --languages=-javascript,sql
mv .git/tags.$$ .git/tags
