#!/usr/bin/env sh
set -e
PATH="/usr/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=all --fields=+l
mv "$dir/$$.tags" "$dir/tags"
